### ISSUE TITLE
HTTPS and Hotlinking

### ISSUE THREAD

**Issue by Uricorn** [AlexMedia/oovg-greenshot#1]
Hey Alex,

I don't know who maintains oo.vg, but I have a feeling you might.

Do you think it's possible to get it to be HTTPS and also for uploaded images to have links like https://oo.vg/image.png so they can be hotlinked?

Also if that is done can you update this plugin so it works with the changes?
I don't want to use imgur anymore :)

Thanks!

**Comment by AlexMedia** [comment]
Hi Uri,

Glad to hear you like oo.vg, I've been getting tired of Imgur as well lately. I'll ask around, and I'll update this plugin when HTTPS comes to oo.vg.

Cheers!

**Comment by Uricorn** [comment]
That was fast. Great :D

**Comment by AlexMedia** [comment]
Sorry for taking so long to implement this, I forgot about it 😊 

If you updated to the latest release ([1.0.21](https://github.com/AlexMedia/oovg-greenshot/releases/tag/1.0.21)), uploads will now go over HTTPS and the returned URL will also be HTTPS.

The URLs themselves are generated by oo.vg and are beyond my control, unfortunately.

**Comment by Uricorn** [comment]
Thanks - installed the update. :)
